### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by mnesarco** [schlangster/cpp.react#27]
This project looks just to what I need for a project, but last update is from 2017, the readme states:

> I'm currently in the process of rewriting the library more or less from scratch and many things are still broken or outdated.

Apparetly this is not maintaned anymore. :(

**Comment by YarikTH** [comment]
@mnesarco  Yes, this project is dead.
Btw, if you need only single thread values propagation without MT and without events and algorithms, then I started https://github.com/YarikTH/ureact for this. But I have no idea when I make it production-ready. Now it works, but it is in early alpha and all from headers to interfaces are subject to change.

**Comment by BlueSolei** [comment]
A guy name [Juan Pedro](https://github.com/arximboldi) promotes value-oriented design, which is along these lines of reactive programming paradigms.
He has a few libraries, one of them is [zug](https://github.com/arximboldi/zug), which is the reactive part.
[Here](www.youtube.com/watch?v=e2-FRFEx8CA) is a great talk about this beautiful new world :-)

**Comment by BlueSolei** [comment]
Which library?

**Comment by mnesarco** [comment]
@BlueSolei It is not open source unfortunately.

**Comment by BlueSolei** [comment]
I actually meant to ask which parts of stlab you use in your library?
It is good to know which tools people use to build such a library.

**Comment by mnesarco** [comment]
Oh, I am sorry for the misunderstanding. I use the Concurrency library.
