### ISSUE TITLE
possible bug in EngineInterface

### ISSUE THREAD

**Issue by stevelorimer** [schlangster/cpp.react#8]
///////////////////////////////////////////////////////////////////////////////////////////////////
	/// EngineInterface - Static wrapper for IReactiveEngine
	///////////////////////////////////////////////////////////////////////////////////////////////////
	template
	<
	    typename D,
	    typename TEngine
	>
	struct EngineInterface
	{
	    static void OnTurnAdmissionStart(TurnT& turn)
	    {
	        Instance().OnTurnAdmissionEnd(turn); // <-- is this a bug? should it call *Start* not *End*?
	    }

**Comment by schlangster** [comment]
Thanks. Yes, it was a bug, but it it did not have any effects, because currently no engine does anything in OnTurnAdmissionStart.
